# Assignment 01: More Practice With GeoPandas

## BIO597 Spatial Analysis of Biodiversity

This assignment gives you more practice with the workflow from Lab 01:

* load a CSV file of species occurrence records
* turn longitude and latitude columns into point geometry
* plot occurrence records on an interactive map
* combine multiple species into one `GeoDataFrame`
* run a few simple spatial summaries

You should expect to write some code in this notebook. Some cells are partly filled in, but you will need to complete the missing pieces.

Remember, learning to code is often times about learning how to strategically copy/paste/modify. At first everything will seem arbitrary, but with repetition it will become common-place and will begin to make sense.

**Assignment 01 is due by next Thursday Sept 10th at 5pm**

## Data

Use the coordinate files in `../labs/EasternSnakes`. Each CSV file has the same basic structure:

* `ID`: occurrence record identifier
* `Longitude`: east-west coordinate
* `Latitude`: north-south coordinate

Because this assignment notebook is in the `assignments` folder, the file paths below start with `../labs/EasternSnakes/`.

## 1. Import the packages

We need `geopandas` for geospatial data and `pandas` for combining tables. Run this cell before running the rest of the notebook.

In [1]:
import geopandas as gpd
import pandas as pd

## 2. Load the first species table

Start with corn snake, *Pantherophis guttatus*. The first goal is only to read the CSV file and inspect the first few rows.

Complete the filename in the first line, then run the cell.

In [4]:
pguttatus_csv = "../labs/EasternSnakes/Pguttatus_coords.csv"

pguttatus_df = gpd.read_file(pguttatus_csv)
pguttatus_df.head()

            ID    Longitude    Latitude
0     LSU99213  -93.2097528  30.6562667
1     OMNH9224    -99.84569     35.0155
2     OMNH8361    -93.82875     34.4087
3  FLMNH153506    -90.89277   31.886388
4  FLMNH151609  -104.399627   33.392876

## 3. Convert the first species to a GeoDataFrame

The table has longitude and latitude columns, but those columns are not yet geometry. Use `gpd.points_from_xy()` to make point geometry.

Fill in the longitude and latitude column names. Look back at the output from the previous cell if you need a reminder.

In [5]:
pguttatus_gdf = gpd.GeoDataFrame(
    pguttatus_df,
    geometry=gpd.points_from_xy(pguttatus_df["Longitude"], pguttatus_df["Latitude"]),
    crs="EPSG:4326",
)

pguttatus_gdf["Species"] = "Pantherophis guttatus"
pguttatus_gdf.head()

,ID,Longitude,Latitude,geometry,Species
0,LSU99213,-93.2097528,30.6562667,POINT (-93.20975 30.65627),Pantherophis guttatus
1,OMNH9224,-99.84569,35.0155,POINT (-99.84569 35.0155),Pantherophis guttatus
2,OMNH8361,-93.82875,34.4087,POINT (-93.82875 34.4087),Pantherophis guttatus
3,FLMNH153506,-90.89277,31.886388,POINT (-90.89277 31.88639),Pantherophis guttatus
4,FLMNH151609,-104.399627,33.392876,POINT (-104.39963 33.39288),Pantherophis guttatus

## 4. Map the first species

Use `.explore()` to make a quick interactive map. This is a visual check that the coordinates are being interpreted correctly.

In [6]:
pguttatus_gdf.explore()

## 5. Repeat the workflow for a second species

Now load common kingsnake, *Lampropeltis getula*. This cell should do two things: read the CSV and show the first few rows.

Fill in the filename.

In [7]:
lgetula_csv = "../labs/EasternSnakes/Lgetula_coords.csv"

lgetula_df = gpd.read_file(lgetula_csv)
lgetula_df.head()

          ID   Longitude   Latitude
0   KU289566   -92.02992   32.55354
1  MVZ175927   -78.76421   35.72642
2  MVZ137799    -82.2377    32.7824
3  OMNH12624  -97.218056  35.220833
4   OMNH5006   -95.98857   34.46144

## 6. Convert the second species to a GeoDataFrame

Use the same pattern from the first species. Make sure the `Species` column contains the correct scientific name.

In [8]:
lgetula_gdf = gpd.GeoDataFrame(
    lgetula_df,
    geometry=gpd.points_from_xy(lgetula_df["Longitude"], lgetula_df["Latitude"]),
    crs="EPSG:4326",
)

lgetula_gdf["Species"] = "Lampropeltis getula"
lgetula_gdf.head()

,ID,Longitude,Latitude,geometry,Species
0,KU289566,-92.02992,32.55354,POINT (-92.02992 32.55354),Lampropeltis getula
1,MVZ175927,-78.76421,35.72642,POINT (-78.76421 35.72642),Lampropeltis getula
2,MVZ137799,-82.2377,32.7824,POINT (-82.2377 32.7824),Lampropeltis getula
3,OMNH12624,-97.218056,35.220833,POINT (-97.21806 35.22083),Lampropeltis getula
4,OMNH5006,-95.98857,34.46144,POINT (-95.98857 34.46144),Lampropeltis getula

## 7. Map the second species

Create an interactive map for *Lampropeltis getula*.

In [9]:
# Replace the blank with the GeoDataFrame you created above.
lgetula_gdf.explore()

## 8. Add a third species

Choose coachwhip, *Masticophis flagellum*. This time, write most of the code yourself.

Your cell should:

* load `Mflagellum_coords.csv`
* convert it to a `GeoDataFrame`
* add a `Species` column
* show the first few rows

In [12]:
mflagellum_csv = "../labs/EasternSnakes/Mflagellum_coords.csv"

mflagellum_df = gpd.read_file(mflagellum_csv)
mflagellum_df.head()

mflagellum_gdf = gpd.GeoDataFrame(
   mflagellum_df,
    geometry=gpd.points_from_xy(mflagellum_df["Longitude"], mflagellum_df["Latitude"]),
    crs="EPSG:4326",
)

mflagellum_gdf["Species"] = "Masticophis flagellum"
mflagellum_gdf.head()

,ID,Longitude,Latitude,geometry,Species
0,AMCC266297,-84.36819,31.32126,POINT (-84.36819 31.32126),Masticophis flagellum
1,AMCC266279,-85.02119,31.67147,POINT (-85.02119 31.67147),Masticophis flagellum
2,AMCC266288,-81.44868,27.85655,POINT (-81.44868 27.85655),Masticophis flagellum
3,AMCC266300,-83.51659,32.66002,POINT (-83.51659 32.66002),Masticophis flagellum
4,AMCC266302,-82.50691,32.03915,POINT (-82.50691 32.03915),Masticophis flagellum

## 9. Map the third species

Make an interactive map for the third species.

In [13]:

mflagellum_gdf.explore()

## 10. Combine the three species

Use `pd.concat()` to combine the three GeoDataFrames into one object. Keep this cell focused on combining the data and checking the result.

In [14]:
combined_snakes = pd.concat([mflagellum_gdf, lgetula_gdf, pguttatus_gdf ])

combined_snakes.head()

,ID,Longitude,Latitude,geometry,Species
0,AMCC266297,-84.36819,31.32126,POINT (-84.36819 31.32126),Masticophis flagellum
1,AMCC266279,-85.02119,31.67147,POINT (-85.02119 31.67147),Masticophis flagellum
2,AMCC266288,-81.44868,27.85655,POINT (-81.44868 27.85655),Masticophis flagellum
3,AMCC266300,-83.51659,32.66002,POINT (-83.51659 32.66002),Masticophis flagellum
4,AMCC266302,-82.50691,32.03915,POINT (-82.50691 32.03915),Masticophis flagellum

## 11. Map all three species together

Map the combined data. Color the points by the `Species` column so the species are easier to compare. Choose a different colormap to color these points from the [python colormap reference](https://matplotlib.org/stable/gallery/color/colormap_reference.html).

In [46]:
combined_snakes.explore(column="Species", cmap= ("viridis"))

## 12. Count the records for each species

A very basic summary is the number of occurrence records per species. Use `groupby()` with the `Species` column.

In [41]:
record_counts = combined_snakes.groupby("Species").size()
record_counts

Species
Lampropeltis getula      35
Masticophis flagellum     9
Pantherophis guttatus    36
dtype: int64

## 13. Find the overall coordinate bounds

`total_bounds` gives the smallest rectangle that contains all the points. The output is four numbers: minimum longitude, minimum latitude, maximum longitude, and maximum latitude.

Run the cell, then answer the question in the markdown cell below it.

In [44]:
combined_snakes.total_bounds

array([-108.2453    ,   26.46783333,  -76.14169   ,   39.61078   ])

**Question:** Based on `total_bounds`, what is the approximate western edge, eastern edge, southern edge, and northern edge of these combined records?

**Your answer:** Western: Juarez; Eastern: Raleigh; Northern: Kanasas City; Southern: Reynosa, Mexico

## 14. Project the data before measuring area

Longitude and latitude are measured in degrees. Area measured in degrees is not easy to interpret, so project the data to `EPSG:5070` before calculating polygon areas.

In [47]:
combined_projected = combined_snakes.to_crs("EPSG:5070")
combined_projected.crs

<Projected CRS: EPSG:5070>
Name: NAD83 / Conus Albers
Axis Info [cartesian]:
- X[east]: Easting (metre)
- Y[north]: Northing (metre)
Area of Use:
- name: United States (USA) - CONUS onshore - Alabama; Arizona; Arkansas; California; Colorado; Connecticut; Delaware; Florida; Georgia; Idaho; Illinois; Indiana; Iowa; Kansas; Kentucky; Louisiana; Maine; Maryland; Massachusetts; Michigan; Minnesota; Mississippi; Missouri; Montana; Nebraska; Nevada; New Hampshire; New Jersey; New Mexico; New York; North Carolina; North Dakota; Ohio; Oklahoma; Oregon; Pennsylvania; Rhode Island; South Carolina; South Dakota; Tennessee; Texas; Utah; Vermont; Virginia; Washington; West Virginia; Wisconsin; Wyoming.
- bounds: (-124.79, 24.41, -66.91, 49.38)
Coordinate Operation:
- name: Conus Albers
- method: Albers Equal Area
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

## 15. Make a convex hull for each species

A convex hull is a simple polygon drawn around a set of points. It is not the true species range, but it is a useful first practice tool.

This cell does three things: groups records by species, turns each group into a convex hull, and maps the hulls.

In [48]:
hulls_projected = combined_projected.dissolve(by="Species")
hulls_projected = hulls_projected.reset_index()

hulls_projected["geometry"] = hulls_projected.geometry.convex_hull

hulls = hulls_projected.to_crs(combined_snakes.crs)
hulls.explore(column="Species", cmap="rainbow")

## 16. Calculate convex hull area

`hulls_projected.area` gives area in square meters because `EPSG:5070` uses meters. Divide by 1,000,000 to convert square meters to square kilometers.

Fill in the missing column name.

In [49]:
hulls["convex_hull_area_km2"] = hulls_projected.area / 1000000

hulls[["Species", "convex_hull_area_km2"]]

                 Species  convex_hull_area_km2
0    Lampropeltis getula          1.670557e+06
1  Masticophis flagellum          1.102008e+05
2  Pantherophis guttatus          3.122832e+06

**Question:** Which species has the largest convex hull area in your result? Give one biological or sampling reason why a species might have a larger hull area than another species.

**Your answer:** P. guttatus has the largest convex hull area. This species seems to be much brighter in color than the other two, so sampling could be biased towards the species that is easier to spot, leading to more instances of this species being recorded.

## 17. Choose one more species

Choose one additional CSV file from `../labs/EasternSnakes` that you did not already use. Load it, convert it to a `GeoDataFrame`, add a `Species` column, and map it.

This is meant to check that you can repeat the workflow without step-by-step scaffolding.

In [52]:
fabacura_csv = "../labs/EasternSnakes/Fabacura_coords.csv"

fabacura_df = gpd.read_file(fabacura_csv)
fabacura_df.head()

fabacura_gdf = gpd.GeoDataFrame(
    fabacura_df,
    geometry=gpd.points_from_xy(fabacura_df["Longitude"], fabacura_df["Latitude"]),
    crs="EPSG:4326",
)

fabacura_gdf["Species"] = "Farancia abacura"
fabacura_gdf.head()

fabacura_gdf.explore()

## 18. What are one or two other interesting biological questions you could ask about this data?

In [ ]:
How do snake traits like color and pattern impact their distribution across different habitat types?

## 19. Submit your work

Before submitting, make sure you have run the notebook from top to bottom and answered the written questions.

Commit and push your completed notebook to your class GitHub repository.